package bruce.roflcraft.rpg.character.stats;

public enum SkillIndex 
{
	SKILL_NATURE,
	SKILL_MINING,
	SKILL_DIGGING,
	SKILL_MELE_DAMAGE,
	SKILL_MELE_SPEED,
	SKILL_BLOCKING,
	SKILL_ARCHERY,
	SKILL_CARPENTERY,
	SKILL_SMITHING,
	SKILL_MASONARY,
	SKILL_SURVIVAL,
	SKILL_SCOLLARSHIP
}
